services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../:/opt/airflow/project
      - ./keys:/keys:ro
      - ./requirements.txt:/requirements.txt
      - ../service_account.json:/opt/airflow/service_account.json:ro
      - ../dbt:/opt/airflow/dbt
    ports:
      - "8080:8080"
    command: >
      bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
      airflow webserver
      "
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../:/opt/airflow/project
      - ./keys:/keys:ro
      - ./requirements.txt:/requirements.txt
      - ../service_account.json:/opt/airflow/service_account.json:ro
      - ../dbt:/opt/airflow/dbt
    command: >
      bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      airflow scheduler
      "
    restart: always

volumes:
  postgres-db-volume:

